name: LowRankLatentGMMs
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - cudatoolkit
  - matplotlib
  - numpy<2.0.0
  - pandas<2.0
  - pip
  - pytorch
  - torchvision
  - scikit-learn
  - pip:
    - torchcfm
    - gdown
