name: LowRankLatentGMMs
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.11
  - cudatoolkit
  - matplotlib
  - numpy
  - pip
  - pytorch
  - torchvision
  - scikit-learn
  - pip:
    - torchcfm
    - gdown
