name: LowRankLatentGMMs
channels:
  - defaults
dependencies:
  - python=3.11
  - matplotlib
  - numpy
  - pandas
  - pip
  - pytorch
  - torchvision
  - torchdiffeq
  - scikit-learn
  - pip:
    - nflows
