#python3 train_images.py --base "MPPCA" --flow "OTCFM" --dataset "cifar10"
#python3 train_images.py --base "Normal" --flow "OTCFM" --dataset "cifar10"
#python3 train_images.py --base "MPPCA" --flow "VPCFM" --dataset "cifar10"
#python3 train_images.py --base "Normal" --flow "VPCFM" --dataset "cifar10"
#python3 train_images.py --base "MPPCA" --flow "CFM" --dataset "cifar10"
#python3 train_images.py --base "Normal" --flow "CFM" --dataset "cifar10"

#python3 train_images.py --base "MPPCA" --flow "OTCFM" --dataset "celeba"
#python3 train_images.py --base "Normal" --flow "OTCFM" --dataset "celeba"
#python3 train_images.py --base "MPPCA" --flow "VPCFM" --dataset "celeba"
#python3 train_images.py --base "Normal" --flow "VPCFM" --dataset "celeba"
#python3 train_images.py --base "MPPCA" --flow "CFM" --dataset "celeba"
#python3 train_images.py --base "Normal" --flow "CFM" --dataset "celeba"

python3 train_images.py --base "MPPCA" --flow "OTCFM" --dataset "fashion"
python3 train_images.py --base "Normal" --flow "OTCFM" --dataset "fashion"
python3 train_images.py --base "MPPCA" --flow "VPCFM" --dataset "fashion"
python3 train_images.py --base "Normal" --flow "VPCFM" --dataset "fashion"
#python3 train_images.py --base "MPPCA" --flow "CFM" --dataset "fashion"
#python3 train_images.py --base "Normal" --flow "CFM" --dataset "fashion"

#python3 train_images.py --base "MPPCA" --flow "OTCFM" --dataset "fgvc-aircraft"
#python3 train_images.py --base "Normal" --flow "OTCFM" --dataset "fgvc-aircraft"
#python3 train_images.py --base "MPPCA" --flow "VPCFM" --dataset "fgvc-aircraft"
#python3 train_images.py --base "Normal" --flow "VPCFM" --dataset "fgvc-aircraft"
#python3 train_images.py --base "MPPCA" --flow "CFM" --dataset "fgvc-aircraft"
#python3 train_images.py --base "Normal" --flow "CFM" --dataset "fgvc-aircraft"

#python3 train_uci.py --base "MPPCA"  --flow "OTCFM" --dataset "POWER"
#python3 train_uci.py --base "Normal"  --flow "OTCFM" --dataset "POWER"
#python3 train_uci.py --base "MPPCA"  --flow "VPCFM" --dataset "POWER"
#python3 train_uci.py --base "Normal"  --flow "VPCFM" --dataset "POWER"
#python3 train_uci.py --base "MPPCA"  --flow "CFM" --dataset "POWER"
#python3 train_uci.py --base "Normal"  --flow "CFM" --dataset "POWER"

#python3 train_uci.py --base "MPPCA"  --flow "OTCFM" --dataset "GAS"
#python3 train_uci.py --base "Normal"  --flow "OTCFM" --dataset "GAS"
#python3 train_uci.py --base "MPPCA"  --flow "VPCFM" --dataset "GAS"
#python3 train_uci.py --base "Normal"  --flow "VPCFM" --dataset "GAS"
#python3 train_uci.py --base "MPPCA"  --flow "CFM" --dataset "GAS"
#python3 train_uci.py --base "Normal"  --flow "CFM" --dataset "GAS"

#python3 train_uci.py --base "MPPCA"  --flow "OTCFM" --dataset "HEPMASS"
#python3 train_uci.py --base "Normal"  --flow "OTCFM" --dataset "HEPMASS"
#python3 train_uci.py --base "MPPCA"  --flow "VPCFM" --dataset "HEPMASS"
#python3 train_uci.py --base "Normal"  --flow "VPCFM" --dataset "HEPMASS"
#python3 train_uci.py --base "MPPCA"  --flow "CFM" --dataset "HEPMASS"
#python3 train_uci.py --base "Normal"  --flow "CFM" --dataset "HEPMASS"

#python3 train_uci.py --base "MPPCA"  --flow "OTCFM" --dataset "MINIBOONE"
#python3 train_uci.py --base "Normal"  --flow "OTCFM" --dataset "MINIBOONE"
#python3 train_uci.py --base "MPPCA"  --flow "VPCFM" --dataset "MINIBOONE"
#python3 train_uci.py --base "Normal"  --flow "VPCFM" --dataset "MINIBOONE"
#python3 train_uci.py --base "MPPCA"  --flow "CFM" --dataset "MINIBOONE"
#python3 train_uci.py --base "Normal"  --flow "CFM" --dataset "MINIBOONE"

#python3 train_uci.py --base "MPPCA"  --flow "OTCFM" --dataset "BSDS300"
#python3 train_uci.py --base "Normal"  --flow "OTCFM" --dataset "BSDS300"
#python3 train_uci.py --base "MPPCA"  --flow "VPCFM" --dataset "BSDS300"
#python3 train_uci.py --base "Normal"  --flow "VPCFM" --dataset "BSDS300"
#python3 train_uci.py --base "MPPCA"  --flow "CFM" --dataset "BSDS300"
#python3 train_uci.py --base "Normal"  --flow "CFM" --dataset "BSDS300"